window.DEMO_DATA = {
  "RC": [
    {
      "_row": 4,
      "cliente": "ANGLOAMERICAN",
      "objetivo": "TECHNO-MAG CU",
      "contacto": "GUILLERMO GUZMAN",
      "etapa": "Seguimiento propuesta",
      "estimacion": 5000.0,
      "avance": 0.65,
      "precio": 931.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Se entregaron 50 kilos para prueba.",
      "comentarios": "Durante este mes se debería utilizar.",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 5,
      "cliente": "ANGLOAMERICAN",
      "objetivo": "DRI-CAST 581A",
      "contacto": "GUILLERMO GUZMAN",
      "etapa": "Seguimiento propuesta",
      "estimacion": 7000.0,
      "avance": 0.65,
      "precio": 2305.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-15T00:00:00",
      "siguientes": "Se entregaron 44 kilos para prueba.",
      "comentarios": "La aplicación se estima para 15 de Mayo",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 6,
      "cliente": "ANGLOAMERICAN",
      "objetivo": "ECO MAG CR",
      "contacto": "GUILLERMO GUZMAN",
      "etapa": "Reunión",
      "estimacion": 0.0,
      "avance": 0.3,
      "precio": 0.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-29T17:00:00",
      "siguientes": "Confirmación por parte del cliente la forma en la que enviaran los ladrillos ",
      "comentarios": "Relacionado al proyecto reciclaje",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 7,
      "cliente": "ANGLOAMERICAN",
      "objetivo": "RECICLAJE MGO-CR",
      "contacto": "GUILLERMO GUZMAN",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Se verifica en terreno la factibilidad",
      "comentarios": "Se debe definir logística para el transporte",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 8,
      "cliente": "ALTONORTE",
      "objetivo": "IUNGTECH 85CR-SC",
      "contacto": "CLAUDIO MORA",
      "etapa": "Contacto",
      "estimacion": 25000.0,
      "avance": 0.1,
      "precio": 2428.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Concretar reunión",
      "comentarios": "SE DEFINE POR PRECIO",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 9,
      "cliente": "ALTONORTE",
      "objetivo": "ECO MAG CR",
      "contacto": "CLAUDIO MORA",
      "etapa": "Contacto",
      "estimacion": null,
      "avance": 0.1,
      "precio": 0.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Concretar reunión",
      "comentarios": "PRUEBA GRATIS",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 10,
      "cliente": "ALTONORTE",
      "objetivo": "PRECAST CPS",
      "contacto": "CLAUDIO MORA",
      "etapa": "Propuesta enviada",
      "estimacion": 40000.0,
      "avance": 0.5,
      "precio": 13648800,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-15T00:00:00",
      "siguientes": "Enviar propuesta actualizada 2026",
      "comentarios": "Enviar propuesta actualizada 2026",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 11,
      "cliente": "ALTONORTE",
      "objetivo": "PRECAST CPS FULL",
      "contacto": "CLAUDIO MORA",
      "etapa": "Reunión",
      "estimacion": 60000.0,
      "avance": 0.3,
      "precio": 19740000,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-06-15T00:00:00",
      "siguientes": "Enviar propuesta",
      "comentarios": "Cerrar tema por boca de 3 piezas antes.",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 12,
      "cliente": "ESCO",
      "objetivo": "IUNKAST 95 PLUS",
      "contacto": "JAVIER GALLARDO",
      "etapa": "Seguimiento propuesta",
      "estimacion": 42000.0,
      "avance": 0.65,
      "precio": 2375.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Se confirma con análisis qmco idoneidad",
      "comentarios": "Falta aprobación de cliente para prueba de tapa completa",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 13,
      "cliente": "ESCO",
      "objetivo": "TECHNOPLAST 1750GR",
      "contacto": "JAVIER GALLARDO",
      "etapa": "Seguimiento propuesta",
      "estimacion": 100000.0,
      "avance": 0.65,
      "precio": 934.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-15T00:00:00",
      "siguientes": "Retomar prueba",
      "comentarios": "Falta confirmar aplicación y resultado",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 14,
      "cliente": "ESCO",
      "objetivo": "ZONA DELTA",
      "contacto": "JAVIER GALLARDO",
      "etapa": "Seguimiento propuesta",
      "estimacion": 15000.0,
      "avance": 0.65,
      "precio": 2350000.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-15T00:00:00",
      "siguientes": "Seguimiento a oferta",
      "comentarios": "En espera de confirmación del cliente",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 15,
      "cliente": "ESCO",
      "objetivo": "BUZA",
      "contacto": "JAVIER GALLARDO",
      "etapa": "Reunión",
      "estimacion": 10000.0,
      "avance": 0.3,
      "precio": 56400.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-14T17:00:00",
      "siguientes": "Seguimiento a oferta",
      "comentarios": "En espera de confirmación del cliente",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 16,
      "cliente": "PROTECO",
      "objetivo": "DRI-VIBE 432 CU",
      "contacto": "CHRISTIAN RAMDOHR",
      "etapa": "Finalizada",
      "estimacion": 27000.0,
      "avance": 1.0,
      "precio": 3078.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-02-14T16:00:00",
      "siguientes": "Consultar potencial",
      "comentarios": "Cerrado por 2026",
      "mercado": "Distribuidor",
      "resultado": null
    },
    {
      "_row": 17,
      "cliente": "TALLERES",
      "objetivo": "T-COAT 692M",
      "contacto": "DIEGO ROSSEL",
      "etapa": "Reunión",
      "estimacion": 70000.0,
      "avance": 0.3,
      "precio": 1455.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Retomar prueba y resultados",
      "comentarios": "En espera de confirmación del cliente",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 18,
      "cliente": "TALLERES",
      "objetivo": "MELTZONA LOCAL",
      "contacto": "DIEGO ROSSEL",
      "etapa": "Contacto",
      "estimacion": null,
      "avance": null,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Ya se contactó al cliente",
      "comentarios": "En espera de confirmación del cliente",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 19,
      "cliente": "VULCO",
      "objetivo": "DRI-VIBE 985A",
      "contacto": "CLAUDIO INFANTE",
      "etapa": "Seguimiento propuesta",
      "estimacion": 35000.0,
      "avance": 0.65,
      "precio": 1867.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Instalación realizada 6 de Mayo",
      "comentarios": "A la espera de puesta en marcha de horno",
      "mercado": "Fundición",
      "resultado": null
    },
    {
      "_row": 20,
      "cliente": "TALLERES",
      "objetivo": "TAB MD 9X4,5X1,25\"",
      "contacto": "CESAR DELGADO",
      "etapa": "Finalizada",
      "estimacion": 3270000.0,
      "avance": 1.0,
      "precio": 1635.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-09T17:00:00",
      "siguientes": "Asignada a Iunge",
      "comentarios": "Asignada a Iunge",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 21,
      "cliente": "TALLERES",
      "objetivo": "TAB MD 9X4,5X1\"",
      "contacto": "CESAR DELGADO",
      "etapa": "Finalizada",
      "estimacion": 6129000.0,
      "avance": 1.0,
      "precio": 2043.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-09T17:00:00",
      "siguientes": "Asignada a Iunge",
      "comentarios": "Asignada a Iunge",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 22,
      "cliente": "TALLERES",
      "objetivo": "CUCHARA MONOLITICA",
      "contacto": "DIEGO ROSSEL",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Presentar propuesta",
      "comentarios": "Coordinar Precio VS Rendimiento",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 23,
      "cliente": "ALTONORTE",
      "objetivo": "BOOK TILES NAC",
      "contacto": "CLAUDIO MORA",
      "etapa": "Reunión",
      "estimacion": 17979000,
      "avance": 0.3,
      "precio": 5993,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Factibilidad o no",
      "comentarios": "Falta aprobación del formato Iunge por parte del cliente",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 24,
      "cliente": "MOLYCOP",
      "objetivo": "CONCRETO S/C",
      "contacto": "GABRIEL AGUILERA",
      "etapa": "Contacto",
      "estimacion": null,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-29T17:00:00",
      "siguientes": "Homologar Alternativa Iunge",
      "comentarios": "Presentar propuesta luego de confirmación del cliente",
      "mercado": "Otros Minerales",
      "resultado": null
    },
    {
      "_row": 25,
      "cliente": "ALTONORTE",
      "objetivo": "ALTERNATIVA IPSXZ",
      "contacto": "CLAUDIO MORA",
      "etapa": "Contacto",
      "estimacion": null,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-29T17:00:00",
      "siguientes": "Homologar Alternativa Iunge",
      "comentarios": "Presentar propuesta luego de confirmación del cliente",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 26,
      "cliente": "ALTONORTE",
      "objetivo": "NUEVO RDELR",
      "contacto": "CLAUDIO MORA",
      "etapa": "Contacto",
      "estimacion": null,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Solicitar reunión",
      "comentarios": "Indefinido",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 27,
      "cliente": "ALTONORTE",
      "objetivo": "PRECAST REFINOS",
      "contacto": "CLAUDIO MORA",
      "etapa": "Contacto",
      "estimacion": 30000000.0,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-30T00:00:00",
      "siguientes": "Solicitar propuesta a AMP",
      "comentarios": "Presentar propuesta al cliente",
      "mercado": "Cobre",
      "resultado": null
    }
  ],
  "MC": [
    {
      "_row": 4,
      "cliente": "Magotteaux",
      "objetivo": "Material gunning básico",
      "contacto": "Diego Mena/patricio Moraga",
      "etapa": "Seguimiento propuesta",
      "estimacion": 30000.0,
      "avance": 0.65,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-01-15T00:00:00",
      "siguientes": "Estimar costo importación",
      "comentarios": "Esperando respuesta para visita y hacer un check list donde se puede utilizar producto, Detenido , porque cliente tiene pedido Anual listo. Por este año no compraran más, pero la idea es conseguir oportunidad de prueba.",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 5,
      "cliente": "Sodimac",
      "objetivo": "Láscar",
      "contacto": "Rodrigo Fierro",
      "etapa": "Propuesta enviada",
      "estimacion": 75000.0,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-10T00:00:00",
      "siguientes": "Seguimiento",
      "comentarios": "Llego cotización , fata definición ,temas directorio",
      "mercado": "Retail",
      "resultado": null
    },
    {
      "_row": 6,
      "cliente": "Ventanas",
      "objetivo": "Material Boca horno",
      "contacto": "Eduardo Marín/José Nahuelpan",
      "etapa": "Reunión",
      "estimacion": 20000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-15T00:00:00",
      "siguientes": "Esperando nueva visita termino Abril",
      "comentarios": "Solicitada  fecha visita, y se debe enviar mail con datos del producto",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 7,
      "cliente": "Ventanas",
      "objetivo": "Prueba Mezcla Tapón (Tecnomag)",
      "contacto": "Eduardo Marín/José nahuelpan",
      "etapa": "Reunión",
      "estimacion": 10000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-15T00:00:00",
      "siguientes": "Esperando prueba , una vez que entre en funcionamiento el horno antiguo, programar",
      "comentarios": "Solicitada  fecha visita",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 8,
      "cliente": "Refex",
      "objetivo": "Potenciar materiales celulosa",
      "contacto": "Felipe Rubio",
      "etapa": "Reunión",
      "estimacion": 100000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-23T00:00:00",
      "siguientes": "Esperando prueba , una vez que entre en funcionamiento el horno antiguo, programar",
      "comentarios": "Se hablo con Refex para ver  visita  a CMPC",
      "mercado": "Instalador",
      "resultado": null
    },
    {
      "_row": 9,
      "cliente": "Maigas",
      "objetivo": "Recuperar venta 4M",
      "contacto": "Anibal franco",
      "etapa": "Seguimiento propuesta",
      "estimacion": 30000.0,
      "avance": 0.65,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-16T00:00:00",
      "siguientes": "Esperando respuesta de propuesta",
      "comentarios": "Se envia  nueva cotizacion , en espera de respuesta , baja producción y acumulación de productos importados.",
      "mercado": "Retail",
      "resultado": null
    },
    {
      "_row": 10,
      "cliente": "Amesti",
      "objetivo": "Recuperar venta 4M",
      "contacto": "Cristian D Amesti",
      "etapa": "Propuesta enviada",
      "estimacion": 50000.0,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-02T00:00:00",
      "siguientes": "Se envía cotización por fachadas lisas",
      "comentarios": "Se habla con ellos , tienen bastante stock , puede ser que ahí solicten, se indica hacerlo con tiempo. No se ha recibido respuesta.",
      "mercado": "Retail",
      "resultado": null
    },
    {
      "_row": 11,
      "cliente": "Imperial",
      "objetivo": "Láscar",
      "contacto": "Claudio Rodriguez",
      "etapa": "Reunión",
      "estimacion": 20000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-01T00:00:00",
      "siguientes": "tener OC para Lascar",
      "comentarios": "Plazo entrega sacos, detenido por indicaciones de gerencia",
      "mercado": "Retail",
      "resultado": null
    },
    {
      "_row": 12,
      "cliente": "Construmart",
      "objetivo": "Abastecimiento de 4M",
      "contacto": "Diego Stitchk",
      "etapa": "Seguimiento propuesta",
      "estimacion": 10000.0,
      "avance": 0.65,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-02-27T16:00:00",
      "siguientes": "Esperando confirmación de reunión con nuevo jefe de linea",
      "comentarios": "Se cambia jefe de línea/ actualmente conversamos con Gerente, llegará nuevo encargado, pide que lo esperemos , ya que esta con la contingencia del trasnporte. Sin respuesta aún.",
      "mercado": "Retail",
      "resultado": null
    },
    {
      "_row": 13,
      "cliente": "Magotteaux",
      "objetivo": "Abastecimiento de Plastisil",
      "contacto": "Oscar labra/ Fernanda Molina",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-31T00:00:00",
      "siguientes": "Esperando Semana 18/05 para ir hacer prueba.",
      "comentarios": "Confirmar fecha de prueba",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 14,
      "cliente": "Magotteaux",
      "objetivo": "Abastecimiento Zona Delta",
      "contacto": "Diego Mena/Patricio Moraga",
      "etapa": "Reunión",
      "estimacion": 8000.0,
      "avance": 0.3,
      "precio": 8000.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-31T17:00:00",
      "siguientes": "Debemos esperar ir con dibujantes a terminar posibles dudas miercoles 6/05, se verá zona de la tapa , solo ladrillos sin zona delta",
      "comentarios": "Ya se fue a terreno a dibujar , faltan medidas para hacer dibujo y terminar",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 15,
      "cliente": "Bosca",
      "objetivo": "Piezas reparación de estufas",
      "contacto": "Alejandro Ulloa",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": null,
      "siguientes": "Ver que pack de reparación de estufas podemos hacer",
      "comentarios": "Ver tipos - modelos de estufas",
      "mercado": "Retail",
      "resultado": null
    }
  ],
  "FF": [
    {
      "_row": 4,
      "cliente": "ENAP",
      "objetivo": "Atchtem",
      "contacto": "Manuel Salas",
      "etapa": "Contacto",
      "estimacion": 4500.0,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-09T00:00:00",
      "siguientes": "Reunión Manuel Salas",
      "comentarios": "Estimar costo importación",
      "mercado": "Energía",
      "resultado": null
    },
    {
      "_row": 5,
      "cliente": "Chuquicamata",
      "objetivo": "Piezas preformadas ",
      "contacto": "Richard Blamey/Mauricio Pulgar",
      "etapa": "Reunión",
      "estimacion": 38000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-02-04T00:00:00",
      "siguientes": "Agendar reunión",
      "comentarios": "Ajustar diseño pieza según requerimientos usurario",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 6,
      "cliente": "Inacal Ant",
      "objetivo": "Z77",
      "contacto": "José Sanhueza",
      "etapa": "Propuesta enviada",
      "estimacion": 5700.0,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-25T00:00:00",
      "siguientes": "Seguimiento propuesta",
      "comentarios": "Cambio persona clave",
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 7,
      "cliente": "Inacal Cpp",
      "objetivo": "NanoTek 70 ABR",
      "contacto": "Ruben Lazo",
      "etapa": "Finalizada",
      "estimacion": 40000.0,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-07-31T17:00:00",
      "siguientes": "Asistir en prueba",
      "comentarios": "Adjudicados con 5 Ton",
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 8,
      "cliente": "Molymet",
      "objetivo": "Ductos",
      "contacto": "Gonzalo Romero",
      "etapa": "Contacto",
      "estimacion": 10000.0,
      "avance": 0.1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-15T00:00:00",
      "siguientes": "Agendar visita",
      "comentarios": "Nuevo Contacto: Oscar Duran",
      "mercado": "Otros Minerales",
      "resultado": null
    },
    {
      "_row": 9,
      "cliente": "Molynor",
      "objetivo": "Lozas piso horno",
      "contacto": "Alejandro Huanca",
      "etapa": "Propuesta enviada",
      "estimacion": 40000.0,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-18T00:00:00",
      "siguientes": "Propuesta enviada",
      "comentarios": "AH de vacaciones",
      "mercado": "Otros Minerales",
      "resultado": null
    },
    {
      "_row": 10,
      "cliente": "CBB ",
      "objetivo": "Ladrllos Al2O3",
      "contacto": "Marios Rios",
      "etapa": "Finalizada",
      "estimacion": 100000.0,
      "avance": 1,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-04-01T00:00:00",
      "siguientes": "Horno detenido",
      "comentarios": null,
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 11,
      "cliente": "Teniente",
      "objetivo": "Escorificador",
      "contacto": "Mónica Tobar",
      "etapa": "Reunión",
      "estimacion": 40000.0,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-05T16:00:00",
      "siguientes": "Esperando que envíen muestra",
      "comentarios": "Exámen As, agendamos reunión",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 12,
      "cliente": "AZA",
      "objetivo": "Hornos, cucharas, tundishes",
      "contacto": "Juan de Groote",
      "etapa": "Finalizada",
      "estimacion": 150000.0,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-03-08T17:00:00",
      "siguientes": "Elaboración de propuesta con materiales HWI",
      "comentarios": "Espera cotización HWI y confirmación de reunión con AZA",
      "mercado": "Acería",
      "resultado": null
    },
    {
      "_row": 13,
      "cliente": "Teniente",
      "objetivo": "Dri Cast",
      "contacto": "Carlos Soto",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-28T17:00:00",
      "siguientes": "Primera prueba realizada",
      "comentarios": "Espera 2° prueba, interesados por tema seguridad",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 14,
      "cliente": "Teniente",
      "objetivo": "Nuevo labio refino",
      "contacto": "Carlos Soto",
      "etapa": "Seguimiento propuesta",
      "estimacion": 1500.0,
      "avance": 0.65,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-28T17:00:00",
      "siguientes": "Idea de diseño aprobada",
      "comentarios": "Espera diseño AMP",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 15,
      "cliente": "Aclara-Huahcipato",
      "objetivo": "Horno ",
      "contacto": "Luis Saavedra",
      "etapa": "Finalizada",
      "estimacion": 30000.0,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-02-05T16:00:00",
      "siguientes": null,
      "comentarios": "Compraron directo en India",
      "mercado": "Otros",
      "resultado": null
    },
    {
      "_row": 16,
      "cliente": "CBB Teno",
      "objetivo": "Nano Tek EP 30 SiC HS",
      "contacto": "Patricio Moraga",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-04-20T00:00:00",
      "siguientes": "Agendar segunda reunión",
      "comentarios": "Prueba en Agosto",
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 17,
      "cliente": "Cementos Transex",
      "objetivo": "Revestimieto quemador",
      "contacto": "Joel Lazo",
      "etapa": "Finalizada",
      "estimacion": null,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-03-05T16:00:00",
      "siguientes": null,
      "comentarios": null,
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 18,
      "cliente": "ENAP ",
      "objetivo": "Planta de ácido",
      "contacto": "Diego Garrido",
      "etapa": "Propuesta enviada",
      "estimacion": null,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-03-06T00:00:00",
      "siguientes": "Adjudicada",
      "comentarios": "Ingreso en área,  ofreciendo soporte técnico.",
      "mercado": "Energía",
      "resultado": null
    },
    {
      "_row": 19,
      "cliente": "Chuquicamata",
      "objetivo": "Conversión",
      "contacto": "Richard Blamey/Mauricio Pulgar",
      "etapa": "Reunión",
      "estimacion": null,
      "avance": 0.3,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-04-15T00:00:00",
      "siguientes": "Reunión HWI ladrillos básicos y electrofundidos",
      "comentarios": null,
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 20,
      "cliente": "Melón",
      "objetivo": "Prueba ladrillos",
      "contacto": "Marcos Castillo",
      "etapa": "Finalizada",
      "estimacion": null,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-04-07T17:00:00",
      "siguientes": "Preparando propuestas",
      "comentarios": "Pruebas corto-mediano plazo sin posibilidades",
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 21,
      "cliente": "Melón",
      "objetivo": "Concretos ",
      "contacto": "Marcos Castillo",
      "etapa": "Propuesta enviada",
      "estimacion": null,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-06-13T17:00:00",
      "siguientes": "Volver a insistir",
      "comentarios": null,
      "mercado": "Cemento y Cal",
      "resultado": null
    },
    {
      "_row": 22,
      "cliente": "GMT",
      "objetivo": "Ladrillos cámara",
      "contacto": "Proyecto Molycop THNO",
      "etapa": "Finalizada",
      "estimacion": null,
      "avance": 1.0,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-04-09T17:00:00",
      "siguientes": "No adjudicada",
      "comentarios": "Perdida por precios contra instalador de la zona conocido por el mandante",
      "mercado": "Instalador",
      "resultado": null
    },
    {
      "_row": 23,
      "cliente": "Refrastrabe",
      "objetivo": "Iuntech ABR",
      "contacto": "Juan Carlos Renteria",
      "etapa": "Finalizada",
      "estimacion": 23500.0,
      "avance": 1.0,
      "precio": 1.88,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": 0,
      "fecha": "2026-05-04T17:00:00",
      "siguientes": "Entrega material finales de mayo",
      "comentarios": "Nuevo cliente de colombia - Iuntech ABR",
      "mercado": "Instalador",
      "resultado": null
    },
    {
      "_row": 24,
      "cliente": "Codelco",
      "objetivo": "Arcilla",
      "contacto": "Multi-divisional",
      "etapa": "Propuesta enviada",
      "estimacion": null,
      "avance": 0.5,
      "precio": null,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-14T17:00:00",
      "siguientes": "Oferta por portal",
      "comentarios": "Buen plazo",
      "mercado": "Cobre",
      "resultado": null
    },
    {
      "_row": 25,
      "cliente": "Enercom-Albemarle",
      "objetivo": "Mejorar eficiencia ITC",
      "contacto": "Hector Arriagada",
      "etapa": "Reunión",
      "estimacion": 4000.0,
      "avance": 0.3,
      "precio": 3.0,
      "cantidad": null,
      "avanceParcial": null,
      "cumplimiento": null,
      "fecha": "2026-05-28T17:00:00",
      "siguientes": null,
      "comentarios": "Debemos enviar la propuesta",
      "mercado": "Energía",
      "resultado": null
    }
  ]
};
